pipeline {
    agent any
    stages {
        stage('Unit Tests Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        GOCACHE=/tmp/go-cache GOMODCACHE=/tmp/go-mod go test -v ./... | go-junit-report > test-results.xml

                        #Generate coverage report
                        GOCACHE=/tmp/go-cache GOMODCACHE=/tmp/go-mod go test -coverprofile=coverage.out ./...
                        go tool cover -html=coverage.out -o coverage.html

                        mkdir -p reports
                        mv coverage.html reports/
                    '''
                }
            }

            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'Code Coverage Report'
                    ])
                }
            }
        }
        stage ('Unit Tests Frontend') {
            agent {
                docker {
                    image 'node:18'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm install'
                    sh 'npm test -- --watchAll=false'
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }

}