pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building the project...'
                sh 'echo "Compiling source code..."'
                sh 'make build'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'echo "Executing unit tests..."'
                sh 'make test'
            }
        }
    }
}